const S={all:'Все',verified:'Подтверждено',rollout:'Rollout',rare:'Редкое',legacy:'Legacy'};
let data={features:[],changes:[],meta:{}};let state={q:'',category:'all',status:'all',platform:'all'};
const el=id=>document.getElementById(id);
const norm=s=>(s||'').toLowerCase().replace(/ё/g,'е');
async function boot(){const manifest=await fetch('data/manifest.json').then(r=>r.json());const chunks=await Promise.all((manifest.parts||[]).map(p=>fetch('data/'+p).then(r=>r.json())));data={meta:manifest.meta||{},changes:manifest.changes||[],features:chunks.flat()};renderNav();renderStatus();render();renderChanges();el('updatedDate').textContent=data.meta.lastVerified||'—';el('totalCount').textContent=data.features.length;el('verifiedCount').textContent=data.features.filter(x=>x.status==='verified').length;el('rareCount').textContent=data.features.filter(x=>x.status==='rare').length;}
function renderNav(){const cats=['all',...new Set(data.features.map(x=>x.category))];el('categoryNav').innerHTML=cats.map(c=>`<button data-cat="${c}" class="${state.category===c?'active':''}"><span>${c==='all'?'Все разделы':c}</span><span class="count">${c==='all'?data.features.length:data.features.filter(x=>x.category===c).length}</span></button>`).join('');el('categoryNav').querySelectorAll('button').forEach(b=>b.onclick=()=>{state.category=b.dataset.cat;renderNav();render()})}
function renderStatus(){el('statusFilters').innerHTML=Object.entries(S).map(([k,v])=>`<button class="chip ${state.status===k?'active':''}" data-status="${k}">${v}</button>`).join('');el('statusFilters').querySelectorAll('button').forEach(b=>b.onclick=()=>{state.status=b.dataset.status;renderStatus();render()})}
function filtered(){return data.features.filter(x=>{const blob=norm([x.name,x.code,x.category,x.summary,x.details,x.use,x.limits,(x.platforms||[]).join(' '),(x.tags||[]).join(' ')].join(' '));return(!state.q||blob.includes(norm(state.q)))&&(state.category==='all'||x.category===state.category)&&(state.status==='all'||x.status===state.status)&&(state.platform==='all'||(x.platforms||[]).includes(state.platform));}).sort((a,b)=>(a.priority||99)-(b.priority||99)||a.name.localeCompare(b.name,'ru'))}
function render(){const arr=filtered();el('resultsMeta').textContent=`Найдено: ${arr.length} из ${data.features.length}`;el('cards').innerHTML=arr.length?arr.map(card).join(''):`<div class="empty">Ничего не найдено. Сбросьте часть фильтров или попробуйте другое слово.</div>`}
function card(x){return `<article class="card"><div class="card-top"><div><div class="badges"><span class="badge status-${x.status}">${S[x.status]||x.status}</span>${(x.platforms||[]).map(p=>`<span class="badge">${p}</span>`).join('')}</div><h3>${x.name}</h3></div></div><div class="summary">${x.summary}</div><div class="details"><div><b>Что делает</b><span>${x.details}</span></div><div><b>Применение</b><span>${x.use}</span></div><div><b>Ограничения</b><span>${x.limits}</span></div>${x.code?`<div><b>Метод</b><span><code>${x.code}</code></span></div>`:''}</div><div class="source-row"><a href="${x.source}" target="_blank" rel="noopener">Источник ↗</a><small>Проверено: ${x.verified}</small></div></article>`}
function renderChanges(){const list=(data.changes||[]).slice(0,6);el('changesList').innerHTML=list.map(c=>`<div class="change"><time>${c.date}</time><div><strong>${c.title}</strong><p>${c.text}</p></div></div>`).join('')}
el('searchInput').addEventListener('input',e=>{state.q=e.target.value;render()});el('platformFilter').addEventListener('change',e=>{state.platform=e.target.value;render()});el('menuBtn').onclick=()=>el('sidebar').classList.toggle('open');el('themeBtn').onclick=()=>{const root=document.documentElement;const next=root.dataset.theme==='dark'?'light':'dark';root.dataset.theme=next;localStorage.setItem('vkbase-theme',next)};document.documentElement.dataset.theme=localStorage.getItem('vkbase-theme')||'light';document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();el('searchInput').focus()}});boot();
